- app/(auth)/(visit)/_layout.tsx
- app/(auth)/(visit)/visit/[id].tsx
- components/QuestionnaireRenderer.tsx
- components/themed/Button.tsx
This PR integrates:
- [DNG-260](https://denguechat.atlassian.net/browse/DNG-260)
- [DNG-259](https://denguechat.atlassian.net/browse/DNG-259)
- [DNG-247](https://denguechat.atlassian.net/browse/DNG-247)
- [DNG-262](https://denguechat.atlassian.net/browse/DNG-262)
> feat: QA Improvements

- constants/Visit.ts
Small fix to match BE required fields
> fix: Update resourceName

- constants/Visit.ts
Reverts socialappslab/denguechatPlus-mobile#10
> Revert "fix: Update resourceName"

- app/(auth)/(visit)/select-house.tsx
- app/(auth)/(visit)/summary.tsx
- app/(auth)/(visit)/visit/[id].tsx
- assets/i18n/en-US.json
- assets/i18n/es-ES.json
- components/themed/RadioButton.tsx
- components/themed/SelectableList.tsx
- constants/Visit.ts
- types/CheckboxProps.ts
- types/index.ts
- util/index.ts
This PR implements [DNG-251](https://denguechat.atlassian.net/browse/DNG-251)
> feat: Add i18n to visit flow

- app/(auth)/(visit)/final.tsx
- app/(auth)/(visit)/summary.tsx
- assets/i18n/en-US.json
- assets/i18n/es-ES.json
> fix: Adds missing i18n

- app/(auth)/(visit)/select-house.tsx
- app/(auth)/(visit)/summary.tsx
- app/(auth)/(visit)/visit/[id].tsx
- assets/i18n/en-US.json
- assets/i18n/es-ES.json
- components/QuestionnaireRenderer.tsx
- components/themed/Checkbox.tsx
- components/themed/RadioButton.tsx
- components/themed/SelectableList.tsx
- constants/Visit.ts
- context/VisitContext.tsx
- types/CheckboxProps.ts
This PR adds a text field on when clicking on the "Other" option.
> feat: Add other option

- app/(auth)/(visit)/summary.tsx
- app/(auth)/(visit)/visit/[id].tsx
- assets/i18n/es-ES.json
- assets/i18n/pt-PT.json
- components/QuestionnaireRenderer.tsx
- components/themed/SelectableItem.tsx
- config/i18n.ts
- context/VisitContext.tsx
- hooks/useCreateMutation.ts
- types/index.ts
> feat: Adds portugues support

- app/(auth)/(visit)/_layout.tsx
- app/(auth)/(visit)/add-comment.tsx
- app/(auth)/(visit)/visit/[id].tsx
- components/themed/Text.tsx
This PR implements 226, a screen to add page of a visit.
**Demo**
> feat: Add comment to a visit

- app/(auth)/(visit)/summary.tsx
- assets/i18n/en-US.json
- assets/i18n/es-ES.json
- assets/i18n/pt-PT.json
- components/QuestionnaireRenderer.tsx
- tailwind.config.js
- types/index.ts
Implements 227, adds:
- Status and status color
- Container count
- House number
**Demo**
> feat: Visit Registration Summary

- app/(auth)/(visit)/summary.tsx
- components/QuestionnaireRenderer.tsx
This PR fixes `currentValues` being undefined.
> fix: Add fallback to currentValues

- app/(auth)/(visit)/summary.tsx
> fix: Check for undefined

- app/(auth)/(visit)/final.tsx
- app/(auth)/(visit)/summary.tsx
This PR fixes the following:
- "Go back home" button not working
- Summary always showing green color
> fix: Summary and final screen fixes

- app/(auth)/(tabs)/profile.tsx
- app/(auth)/(tabs)/visits.tsx
- app/(auth)/(visit)/_layout.tsx
- app/(auth)/(visit)/add-container.tsx
- app/(auth)/(visit)/select-house.tsx
- app/(auth)/(visit)/summary.tsx
- app/(auth)/(visit)/visit/[id].tsx
- app/_layout.tsx
- components/QuestionnaireRenderer.tsx
- components/themed/ListItem.tsx
- config/axios.ts
- context/AuthProvider.tsx
- context/VisitContext.tsx
- hooks/useVisitStore.ts
- package.json
- types/index.ts
- util/zustandDevTool.tsx
- yarn.lock
This PR implements:
- Add multiple containers ([306](https://denguechat.atlassian.net/browse/DNG-306)).
- Basic offline support (WIP/[302](https://denguechat.atlassian.net/browse/DNG-302)) this PR also includes a flag that's storing visits with offline as default.
- Visits view, with containers pending to synchronise.
> feat: Add multiple containers, offline state and visits view

- app/(auth)/(tabs)/visits.tsx
- components/QuestionnaireRenderer.tsx
- components/segments/OfflineVisitSheet.tsx
> fix: check for array length

- app/(auth)/(tabs)/visits.tsx
- assets/i18n/en-US.json
- assets/i18n/es-ES.json
- assets/i18n/pt-PT.json
- components/segments/OfflineVisitSheet.tsx
Small i18n fix and WIP Segment
> feat: Update copy and add visit segment

- app/(auth)/(visit)/add-container.tsx
> fix: Add disabled button

- app/(auth)/(tabs)/visits.tsx
- app/(auth)/(visit)/add-container.tsx
- assets/i18n/en-US.json
- assets/i18n/es-ES.json
- assets/i18n/pt-PT.json
Small fix on i18n in Add Container View
> fix: Update add container view

- app/(auth)/(tabs)/visits.tsx
- app/(auth)/(visit)/select-house.tsx
- app/(auth)/(visit)/summary.tsx
- components/QuestionnaireRenderer.tsx
- types/index.ts
This PR enables sending visits to summary conditionally depending on the network connection
> Feat: Conditionally submit visits

- app/(auth)/(tabs)/visits.tsx
- app/(auth)/(visit)/summary.tsx
- app/(auth)/(visit)/visit/[id].tsx
- hooks/useVisitStore.ts
This PR lets users synchronise visits in the "Visits" view independently.
> feat: Synchronise visits independently

- app/(auth)/(visit)/summary.tsx
> chore: Remove static isConnected

- app/(auth)/(tabs)/visits.tsx
- app/(auth)/(visit)/final.tsx
- app/(auth)/(visit)/select-house.tsx
- app/(auth)/(visit)/summary.tsx
- assets/i18n/en-US.json
- assets/i18n/es-ES.json
- assets/i18n/pt-PT.json
- components/themed/Button.tsx
- components/themed/ListItem.tsx
- package.json
- util/index.ts
- util/prepareFormData.ts
- yarn.lock
> feat: New summary on offline

- app/(auth)/(visit)/visit/[id].tsx
- components/QuestionnaireRenderer.tsx
- components/themed/SelectableItem.tsx
- types/SelectableItemProps.ts
This PR fixes the following:
- [311](https://denguechat.atlassian.net/browse/DNG-311)
- [359](https://denguechat.atlassian.net/browse/DNG-359)
- [358](https://denguechat.atlassian.net/browse/DNG-358)
- [344](https://denguechat.atlassian.net/browse/DNG-344)
> fix: Misc fixes in questionnaire

- app/(auth)/_layout.tsx
- app/(public)/login.tsx
This PR adds a loading state to #60 (Delete Account)
> feat: Add lodaer

- app/(auth)/(tabs)/visits.tsx
This PR adds [363: House Reports](https://denguechat.atlassian.net/browse/DNG-363)
> feat: Add house reports

- assets/i18n/en-US.json
- assets/i18n/es-ES.json
- assets/i18n/pt-PT.json
This PR fixes the last screen greetings based on [406](https://denguechat.atlassian.net/browse/DNG-406)
> fix: Offline/online locales

- app/(auth)/(tabs)/visits.tsx
- app/(auth)/(visit)/summary.tsx
- components/VisitSummary.tsx
- types/prepareFormData.ts
- util/normalizeVisitData.ts
- util/prepareFormData.ts
This PR solves [396](https://denguechat.atlassian.net/browse/DNG-396), [409](https://denguechat.atlassian.net/browse/DNG-409)
> fix: Synchronize visits

- app/(auth)/(visit)/visit/[id].tsx
- components/QuestionnaireRenderer.tsx
- context/VisitContext.tsx
- hooks/useVisitStore.ts
- types/index.ts
This PR fixes: [403](https://denguechat.atlassian.net/browse/DNG-403), [405](https://denguechat.atlassian.net/browse/DNG-405), [498](https://denguechat.atlassian.net/browse/DNG-398).
> feat: Support stateful cases

- app/(auth)/(visit)/visit/[id].tsx
- util/prepareFormData.ts
This PR fixes a small bug related to container counter
> fix: Imports and container counter

- app/(auth)/(visit)/visit/[id].tsx
- util/prepareFormData.ts
Reverts socialappslab/denguechatPlus-mobile#73
> Revert "fix: Imports and container counter"

- app/(auth)/(visit)/final.tsx
This PR implements [432](https://denguechat.atlassian.net/browse/DNG-432)
> fix: Center final screen

- app/(auth)/(config)/_layout.tsx
- app/(auth)/(config)/filters-visit.tsx
- app/(auth)/(tabs)/_layout.tsx
- app/(auth)/(tabs)/visits.tsx
- app/_layout.tsx
- assets/i18n/en-US.json
- assets/i18n/es-ES.json
- assets/i18n/pt-PT.json
This PR implements [436](https://denguechat.atlassian.net/browse/DNG-436).
> feat: Add filters to visit screen

- app/(auth)/(visit)/sanitizeInspections.ts
- app/(auth)/(visit)/summary.tsx
> fix: Always sanitize

- app.config.js
- app/(auth)/_layout.tsx
- app/(public)/login.tsx
fix: I set DengueChatPlus instead denguechat+
> fix: I set DengueChatPlus instead denguechat+

- app/(auth)/(visit)/visit/[id].tsx
- components/QuestionnaireRenderer.tsx
- context/VisitContext.tsx
- context/questionnaire.json
> fix: (temp) garden/house flows fix

- context/questionnaire.json
This PR fixes [403](https://denguechat.atlassian.net/browse/DNG-403)
> fix: Update to greet

- context/questionnaire.json
> Fix the images in visit flow

- app/(auth)/(visit)/summary.tsx
fix: i used house reference code instead house id
> fix: i used house reference code instead house id

- app/(auth)/(visit)/container-picture.tsx
- app/(auth)/(visit)/visit/[id].tsx
> fix: Request Permission

- app/(auth)/(tabs)/visits.tsx
- app/(auth)/(visit)/final.tsx
- app/(auth)/(visit)/visit/[id].tsx
Fixes [519](https://denguechat.atlassian.net/browse/DNG-519) and [516](https://denguechat.atlassian.net/browse/DNG-516)
> fix: Visit and Site counter updates

- app/(auth)/(tabs)/profile.tsx
> fix: filters on my brigade

- .env
fix: pointing endpoints variables to production
> fix: pointing endpoints variables to production

- assets/i18n/en-US.json
- assets/i18n/es-ES.json
- assets/i18n/pt-PT.json
- schema/index.ts
fix: change team_leader label by facilitator
> fix: change team_leader label by facilitator

- app/(auth)/(chat)/edit-post.tsx
- app/(auth)/(chat)/new-post.tsx
- app/(auth)/(config)/change-brigade-success.tsx
this pr updates `.replace` to `.push` when going back home
> fix: router was replcing in previous version

- config/axios.ts
add a header for when a user tries to log in
> fix: Persistent User Session on Mobile App

- app/(auth)/(visit)/summary.tsx
- hooks/useVisitStore.ts
fixes read-only exception during offline visits
> fix: disable auto freeze

- app/(auth)/(tabs)/_layout.tsx
- app/(public)/login.tsx
- components/themed/useThemeColor.ts
remove `useColorScheme` instances
> fix: force light mode

- util/prepareFormData.ts
[DNG-625](https://denguechat.atlassian.net/browse/DNG-625)
> fix: water-source-other

- app/(auth)/(visit)/summary.tsx
[DNG-659](https://denguechat.atlassian.net/browse/DNG-659)
> fix: add visit permission based on early exit

- app/(auth)/(tabs)/visits.tsx
[DNG-665](https://denguechat.atlassian.net/browse/DNG-665)
> fix: add team to filter count

- app/(auth)/(config)/filters-visit.tsx
[DNG-667](https://denguechat.atlassian.net/browse/DNG-667)
> fix: always go to visits

- app/(auth)/(tabs)/visits.tsx
[DNG-666](https://denguechat.atlassian.net/browse/DNG-666)
> fix: apply all filters on filter update

- .sh/update-build.sh
- app.config.js
- app/(auth)/(tabs)/visits.tsx
- app/(auth)/(visit)/summary.tsx
- context/AuthProvider.tsx
- eas.json
- package.json
- plugins/rollbar-config-plugin/index.js
obs: rollbar is removed on _both_ ios and android
[DNG-565](https://denguechat.atlassian.net/browse/DNG-565)
> feat: add ios to pipeline (remove rollbar)

- app/(auth)/(tabs)/visits.tsx
[DNG-634](https://denguechat.atlassian.net/browse/DNG-637)
> fix: display filter details on visit's chart

- app/(auth)/(config)/_layout.tsx
- app/(auth)/(config)/filters-users.tsx
- app/(auth)/(config)/filters-visit.tsx
- app/(auth)/(config)/select-user.tsx
- app/(auth)/(tabs)/visits.tsx
- app/(auth)/_layout.tsx
- app/_layout.tsx
- components/themed/FilterButton.tsx
- context/FilterContext.tsx
- hooks/useFilters.ts
[DNG-670](https://denguechat.atlassian.net/browse/DNG-670)
> fix: filters navigation

- app/(auth)/(config)/_layout.tsx
- app/(auth)/(config)/filter-brigade-visit.tsx
- app/(auth)/(config)/filter-sector-visit.tsx
- app/(auth)/(config)/filter-wedge-visit.tsx
- app/(auth)/(config)/filters-brigade.tsx
- app/(auth)/(config)/filters-visit.tsx
[DNG-669](https://denguechat.atlassian.net/browse/DNG-669)
> fix: filter context

- app/(auth)/(visit)/visit/[id].tsx
- types/index.ts
becasuse now every question have a new attribute called "required"
> fix: refactor the isValid method,

- app/(auth)/(visit)/summary.tsx
- types/index.ts
- util/prepareFormData.ts
[DNG-697](https://denguechat.atlassian.net/browse/DNG-697)
> fix: host information

- app/_layout.tsx
- metro.config.js
- package.json
- yarn.lock
[DNG-679](https://denguechat.atlassian.net/browse/DNG-679)
> feat: add sentry

- components/QuestionnaireRenderer.tsx
[DNG-722](https://denguechat.atlassian.net/browse/DNG-722)
> fix: use currentValues to make sure all instances re-render

- app/(public)/login.tsx
- assets/i18n/en-US.json
- assets/i18n/es-ES.json
- assets/i18n/pt-PT.json
[DNG-684](https://denguechat.atlassian.net/browse/DNG-684)
This PR prevents users from login while being offline showing an error message. I've also added a missing type and removed an unused variable.
> feat: prevent login if user is offline with error message

- app/(auth)/(visit)/summary.tsx
[DNG-655](https://denguechat.atlassian.net/browse/DNG-655)
> fix: make finalize button in summary page more prominent

- app.config.js
- app/(auth)/(visit)/add-location.tsx
- app/(auth)/(visit)/new-house.tsx
- app/(auth)/(visit)/select-house.tsx
[DNG-535](https://denguechat.atlassian.net/browse/DNG-535)
[DNG-703](https://denguechat.atlassian.net/browse/DNG-703)
> Fix crash when adding a new location, re-enable section

- util/prepareFormData.ts
[DNG-696](https://denguechat.atlassian.net/browse/DNG-696)
> fix: add location

- assets/i18n/en-US.json
- assets/i18n/es-ES.json
- assets/i18n/pt-PT.json
- config/axios.ts
- package.json
- yarn.lock
[DNG-762](https://denguechat.atlassian.net/browse/DNG-762)
> Force updates

- app/(auth)/(tabs)/_layout.tsx
- app/(auth)/_layout.tsx
[DNG-755](https://denguechat.atlassian.net/browse/DNG-755)
> Hide buttons in drawer

- assets/i18n/en-US.json
- assets/i18n/es-ES.json
- assets/i18n/pt-PT.json
[DNG-737](https://denguechat.atlassian.net/browse/DNG-737)
> Change word "post" for "blog" everywhere

- .vscode/launch.json
- app/(auth)/(visit)/sanitizeInspections.ts
- app/(auth)/(visit)/summary.tsx
- components/QuestionnaireRenderer.tsx
- hooks/useCreateMutation.ts
- types/index.ts
- util/prepareFormData.ts
[DNG-734](https://denguechat.atlassian.net/browse/DNG-734)
> Weigthed points for options

- app/(auth)/(tabs)/profile.tsx
- app/(auth)/(tabs)/visits.tsx
- app/(auth)/(visit)/select-house.tsx
[DNG-760](https://denguechat.atlassian.net/browse/DNG-760)
I've also found a bug where the persisted store was not being cleaned on logout causing the offline visits to remain in the visits list even when you logout and login again to another user. @loorely we should create a ticket for that.
> Wrong site number in offline visits

- app/(auth)/(tabs)/visits.tsx
[DNG-780](https://denguechat.atlassian.net/browse/DNG-780)
> Remove hard-coded visit permission

- context/AuthProvider.tsx
[DNG-792](https://denguechat.atlassian.net/browse/DNG-792)
> Change redirection after login from chat to visits page

- app/(auth)/(visit)/summary.tsx
- assets/i18n/en-US.json
- assets/i18n/es-ES.json
- assets/i18n/pt-PT.json
[DNG-793](https://denguechat.atlassian.net/browse/DNG-793)
> Remove edit from start button in summary page

- app/_layout.tsx
[DNG-815](https://denguechat.atlassian.net/browse/DNG-815)
> Make sure we're only sending production events to sentry

- app/(auth)/(visit)/summary.tsx
[DNG-799](https://denguechat.atlassian.net/browse/DNG-799)
> Make finalize button float

- app/(auth)/_layout.tsx
- assets/i18n/en-US.json
- assets/i18n/es-ES.json
- assets/i18n/pt-PT.json
[DNG-811](https://denguechat.atlassian.net/browse/DNG-811)
> Add user guide link in drawer

- app/(public)/login.tsx
- app/_layout.tsx
- assets/i18n/en-US.json
- assets/i18n/es-ES.json
- assets/i18n/pt-PT.json
- components/themed/Toast.tsx
- hooks/useSignIn.ts
- util/index.ts
[DNG-800](https://denguechat.atlassian.net/browse/DNG-800)
> Contextual messages on first 3 failed login attempts

- app/(auth)/(tabs)/visits.tsx
- app/_layout.tsx
- types/index.ts
- util/sanitizeInspections.ts
[DNG-816](https://denguechat.atlassian.net/browse/DNG-816)
> Send water source as multiple values

- types/index.ts
- util/prepareFormData.ts
- util/sanitizeInspections.ts
[DNG-924](https://denguechat.atlassian.net/browse/DNG-924)
> Make the elimination method type multiselect

- app/(auth)/(tabs)/visits.tsx
- assets/i18n/en.json
- assets/i18n/es.json
- assets/i18n/pt.json
- context/VisitContext.tsx
- hooks/useStore.ts
- schema/index.ts
- types/index.ts
[DNG-921](https://denguechat.atlassian.net/browse/DNG-921?atlOrigin=eyJpIjoiOTJjODk3NjIzNjQwNGUzZjg0YzAzMTMwM2JlOTUzZGMiLCJwIjoiaiJ9)
> Add select field to change the onwer of the visit, refactors

- app/(auth)/(tabs)/profile.tsx
- assets/i18n/en.json
- assets/i18n/es.json
- assets/i18n/pt.json
[DNG-956](https://denguechat.atlassian.net/browse/DNG-956)
> Remove "My contribution in points" progress bar

- app/(auth)/(config)/_layout.tsx
- app/(auth)/(config)/change-brigade.tsx
- app/(auth)/(config)/change-house-block.tsx
- app/(auth)/(tabs)/index.tsx
- app/(auth)/(visit)/new-house.tsx
- app/(auth)/(visit)/select-house.tsx
- assets/i18n/en.json
- assets/i18n/es.json
- assets/i18n/pt.json
- components/themed/SelectableItem.tsx
- components/themed/SimpleChip.tsx
- hooks/useHouseBlockLabel.ts
- schema/auth.ts
- types/SelectableItemProps.ts
- types/index.ts
[DNG-942](https://denguechat.atlassian.net/browse/DNG-942)
> Generalize "Frente a Frente" to "House groups"

- app.config.ts
- app/(public)/login.tsx
- app/_layout.tsx
- context/AuthProvider.tsx
- hooks/useSignIn.ts
- metro.config.js
[DNG-999](https://denguechat.atlassian.net/browse/DNG-999)
> Improve sentry integration

- app/(auth)/(tabs)/_layout.tsx
- app/(auth)/(visit)/select-house.tsx
- components/Providers.tsx
- hooks/useStore.ts
- package.json
- yarn.lock
[DNG-977](https://denguechat.atlassian.net/browse/DNG-977)
> Preload house list when the app loads
